include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o


ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo")
obj-y   +=  nt35590_hd720_dsi_cmd_auo.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_wvga")
obj-y   +=  nt35590_hd720_dsi_cmd_auo_wvga.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_fwvga")
obj-y   +=  nt35590_hd720_dsi_cmd_auo_fwvga.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_qhd")
obj-y   +=  nt35590_hd720_dsi_cmd_auo_qhd.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"otm8018b_dsi_vdo_txd_fwvga")
obj-y   +=  otm8018b_dsi_vdo_txd_fwvga.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"ili9806c_dsi_vdo_djn_fwvga")
obj-y   +=  ili9806c_dsi_vdo_djn_fwvga.o
endif
