#ifdef ACCDET_28V_MODE
#undef ACCDET_28V_MODE
#endif

#define ACCDET_EINT
#define ACCDET_LOW_POWER 
#define CUST_EINT_ACCDET_NUM 15
#define ACCDET_SHORT_PLUGOUT_DEBOUNCE 20
#define ACCDET_SHORT_PLUGOUT_DEBOUNCE_CN 20
 
#define ACCDET_MULTI_KEY_FEATURE

#ifdef ACCDET_PIN_RECOGNIZATION
#undef ACCDET_PIN_RECOGNIZATION
#endif 

#define ACCDET_PIN_SWAP
